linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  misspell:
    locale: US
  ireturn:
    allow:
      - error
      - github.com\/osamingo\/checkdigit\.Provider

linters:
  enable-all: true
  disable:
    - mnd
    - varnamelen
    - wsl
    - recvcheck

issues:
  exclude-rules:
    - path: _test\.go
      text: "does not use range value in test Run"
      linters:
        - paralleltest
    - path: _test\.go
      linters:
        - dupl
        - ifshort
        - funlen
        - exhaustruct
        - depguard
