linters-settings:
  errcheck:
    check-type-asserts: true
    check-blank: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - whitespace
    - wsl
    - gomnd
    - forbidigo

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - paralleltest
