sudo: false

language: go
go:
  - 1.11.x
  - 1.12.x

before_install:
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

before_script:
  - golangci-lint run

script:
  - go test -covermode=atomic -coverprofile=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash)
