name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '10 10 * * 0'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.18.x', '1.19.x' ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go test -race -covermode=atomic -coverprofile=coverage.txt ./...
      - uses: codecov/codecov-action@v2
        with:
          file: coverage.txt
          yml: codecov.yml
